name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    build:
        name: Build CROX
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              id: build
              uses: samyarsadat/Pico-Build-Action@v1.3.0
              with:
                  source_dir: "./"
                  output_ext: "*.uf2"
                  cmake_args: "-DPICO_BOARD=pico2 -DPICO_PLATFORM=rp2350"

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v7.0.1
              with:
                  name: workspace_artifacts
                  path: ${{steps.build.outputs.output_dir}}
                  archive: false
